import type { Metadata } from 'next'
import ClientComponent from './ClientComponent'
import './globals.css'
import 'animate.css'

// 元数据
export const metadata: Metadata = {
  title: 'Next-APP',
  description: 'Generated by create next app',
  icons: '/favicon.ico',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <ClientComponent>{children}</ClientComponent>
}
